### ISSUE TITLE
Restore previous slack status instead of clearing it.

### ISSUE THREAD

**Issue by lorenzocestaro** [veloxy/pomodoro-electron#6]
Hi @veloxy , I recently started using this simple and very neat pomodoro app.

When the following conditions are met:
- Slack integration enabled.
- Custom focus slack state in settings

It happens that if the user had a slack status set before starting a pomodoro, that status is lost when the pomodoro ends.

I found myself wanting to keep my previous status when finishing a pomodoro (e.g. 'Working remotely') without the need of resetting every time, so I forked the repo and made a change to accomplish this.

I wanted to see if you might be interested in having this merged. If so, I could also work on adding a checkbox in the settings window to enable/disable the behavior.

**Comment by veloxy** [comment]
Sounds like a good behavior to me, even without the checkbox! I'd merge it!

**Comment by lorenzocestaro** [comment]
There it is. Let me know if there is something I should fix.
I was planning on doing some other changes, maybe I'll get back to you when done.
